### ISSUE TITLE
Should we delete this repository?

### ISSUE THREAD

**Issue by jonjohnsonjr** [opencontainers/artifacts#61]
The guidance [here](https://github.com/opencontainers/artifacts/blob/main/artifact-authors.md#defining-a-unique-artifact-type) is more harmful than if it simply didn't exist.

Encouraging the proliferation of custom mediaTypes (rather than reusing existing, registered types) reduces the ability to reuse software. If your layers are gzipped tarballs, there's no reasons to invent a unique layer media type.

There's no reason to prescribe an opinionated framework on top of RFC 6838. This guidance just obscures what artifact authors _should_ be looking at.

**Comment by vrothberg** [comment]
> The guidance [here](https://github.com/opencontainers/artifacts/blob/main/artifact-authors.md#defining-a-unique-artifact-type) is more harmful than if it simply didn't exist.

What should folks do if they have a legitimate need for creating a new artifact?  I am a bit puzzled by the issue title.

> Encouraging the proliferation of custom mediaTypes (rather than reusing existing, registered types) reduces the ability to reuse software. If your layers are gzipped tarballs, there's no reasons to invent a unique layer media type.

I totally agree.  Existing media types should be reused whenever possible.

**Comment by mikebrow** [comment]
> We should probably delete this repository

Is that guidance from opencontainers/wg-reference-types? I was expecting to see use cases, prototypes built on the wg proposal, for explaining how such custom artifacts should be implemented. Is that part of the workgroup being deleted?

> The guidance [here](https://github.com/opencontainers/artifacts/blob/main/artifact-authors.md#defining-a-unique-artifact-type) is more harmful than if it simply didn't exist.

We plan, on updating guidance based on the wg. output when it arrives and/or if it is accepted by the specs.

We will probably include a map/migration between proposal A and E, for those that engaged early in the year(s) before proposal E existed. 

> Encouraging the proliferation of custom mediaTypes (rather than reusing existing, registered types) reduces the ability to reuse software. If your layers are gzipped tarballs, there's no reasons to invent a unique layer media type.

ok? 

> vrothburg: I totally agree. Existing media types should be reused whenever possible.

100% agree, whenever possible, and not at all cost. 

Jamming everything typed that doesn't fit your one artifact type to rule them all.. into a list of name value pairs (annotations),.. Seems patchy, no?

**Comment by imjasonh** [comment]
My 2c as a non-TOB person, only as a community and WG contributor / meeting attendee / opinion haver: the reference WG does not have the definition of new types of things in its scope and charter, only how things can reference other things. Expanding that WG's scope to include how types of things are expressed and how new types are defined/proposed/specified seems like a distraction, when it's actually finally making progress toward its actual purpose.

Maybe there's room for a "new types WG" but that should be a separate from the references WG (hopefully after, for my meeting attendance tolerance 😅).

In any case, I agree with Jon that the existence of this repo as a non-spec promoted alongside the real specs, ambiguously worded so that it seems more official than it is, is harmful to readers who may not be familiar with its positioning. Luring unaware new users into adhering to this non-spec instead of the already-widely-adopted RFC 6838 will cause problems later if we ever want to make changes to it (including perhaps while making it a real spec!). Based on the discussion in https://github.com/opencontainers/artifacts/pull/56 this ambiguity seems to be intentional, or at least not well understood by this repo's maintainers.

**Comment by sudo-bmitch** [comment]
> We will probably include a map/migration between proposal A and E, for those that engaged early in the year(s) before proposal E existed.

I think migration from anything groups have done separate from the OCI specs to whatever the WG proposes should be left up to those groups to implement themselves. It's not just proposal A, there's also proposal B, and there's no way to know what other things have been created separate from our work here.

If OCI had previously recommended a way to refer from one artifact to another, and we were changing that, then I'd expect us to create a migration plan for that scenario.

**Comment by mikebrow** [comment]
> > We will probably include a map/migration between proposal A and E, for those that engaged early in the year(s) before proposal E existed.
> 
> I think migration from anything groups have done separate from the OCI specs to whatever the WG proposes should be left up to those groups to implement themselves. It's not just proposal A, there's also proposal B, and there's no way to know what other things have been created separate from our work here.
> 
> If OCI had previously recommended a way to refer from one artifact to another, and we were changing that, then I'd expect us to create a migration plan for that scenario.

I understand the point... and I see some evidence this area (artifacts) is still undergoing innovation and debate.

OCI charter mission statement [cite from](https://github.com/opencontainers/tob/blob/main/CHARTER.md#1-mission-of-the-open-container-initiative-oci):

##  1. Mission of the Open Container Initiative (“OCI”).

The Open Container Initiative provides an open source technical community
within which industry participants may easily contribute to building
vendor-neutral, portable and open specifications, reference implementations,
and tools that deliver on the promise of containers as a source of application
portability backed by a certification program.

**The Open Container Initiative does not seek to be a marketing organization,
define a full stack or solution requirements, and will strive to avoid
standardizing technical areas undergoing innovation and debate.**

**Comment by mikebrow** [comment]
> See also [opencontainers/wg-reference-types#62](https://github.com/opencontainers/wg-reference-types/issues/62) where we may want to merge some of the advice here with the schemas being proposed. When that's done, it may make sense to archive this repo to avoid confusion. But this is very forward looking based on things that would need to be approved by lots of people.

true it may .. lots of dominos left to fall

**Comment by afflom** [comment]
What are the implications of the proposed repo deletion on projects/technologies currently leveraging OCI as general content storage?

**Comment by rchincha** [comment]
Clarification (1)?

See that only "vnd.oci.image.manifest.v1+json" has been registered as a IANA media-type [1], while these media-types [3] have been defined in the OCI image **spec** [3]. 

Also, as per RFC 6838 wrt vendor trees [2], as it reads, "OCI" is positioned as a industry consortium which **does not** "qualify as recognized standards-related organization" and hence whatever media-types it comes up get stuffed under vnd.oci.* and further updates don't quite require IANA intervention or arbitration until someone else proposes adding "application/vnd.oci.layout.header.v1+json" without OCI knowledge.

Clarification (2)?

Assuming artifacts and registries are inseparable, should "intelligence" be moved into a registry meaning should the registry become content-aware? Or should the intelligence remain at the client-side (push and pull)? If the former, then some way to select on the content? Either media-type or annotations?

Clarification (3)?

Registries have common use cases, which coincidentally also require registries to become content-aware - security scans, garbage collection, etc. Should there be a one-to-one correspondence between a well-defined media-type (hence "standards") for each use case instead of many different media-types ("proprietary") for the same use case?

"A registry will guarantee GC and referential integrity iff you conform to media-type X" 
(vs) 
"A registry will guarantee GC and referential integrity if media-type X is one of many supported"

References:

[1] https://www.iana.org/assignments/media-types/media-types.xhtml
[2] https://datatracker.ietf.org/doc/html/rfc6838#section-3.2
[3] https://github.com/opencontainers/image-spec/blob/main/media-types.md

**Comment by rchincha** [comment]
@jonjohnsonjr, could you also expand on this a bit?

> This guidance just obscures what artifact authors _should_ be looking at.

**Comment by SteveLasker** [comment]
Closing as the evolution of OCI Artifacts is being covered as a TOB Vote: https://github.com/opencontainers/tob/issues/126
